services:
  postgres:
    image: postgres:latest
    container_name: postgres_task_manager
    environment:
      POSTGRES_DB: task_manager
      POSTGRES_USER: task
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
